### ISSUE TITLE
update lwIP

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2050]
I've updated lwIP to version 2.0.0 which includes the TCP window scaling patch and other improvements. I've also enabled IPv6, but I have not added support for static IPv6 addressing in the libc plugin, nor have I tested automatic addressing yet.

**Comment by ehmry** [comment]
To clarify, I rewrote repos/libports/include/lwip/lwipopts.h to remove any defines that were the same as the default.

**Comment by chelmuth** [comment]
Gave your patch I try but failed...
```
make test/lwip/http_srv
    COMPILE  sys_arch.o
.../repos/libports/src/lib/lwip/platform/sys_arch.cc:194:2: error: #else without #if
 #else
  ^
.../repos/libports/src/lib/lwip/platform/sys_arch.cc:197:2: error: #endif without #if
 #endif /* LWIP_DHCP */
  ^
make[2]: *** [sys_arch.o] Error 1
make[1]: *** [lwip.lib] Error 2
make: *** [gen_deps_and_build_targets] Error 2
```
Branch is chelmuth/issue2050_lwip_update.

**Comment by ehmry** [comment]
@chelmuth fixed at 12969821a46fbf197bb2cc69e81c0f5c237ff0c8 with a clean up of lwipopts.h.

**Comment by chelmuth** [comment]
@ehmry thanks for the fixup but I fear we're still not there. I gave the port some runs on base-linux with the following results
* **lwip 1.4.1**
  * **TCP_STREAM** 195-202 MBit/s
  * **TCP_MAERTS** 59-63 MBit/s
* **lwip 2.0.0**
  * **TCP_STREAM** 49-65 MBit/s
  * **TCP_MAERTS** timeout

Could you please have another look where this discrepancy may originate from?

Also, I spotted that the port uses 2.0.0-RC1. Do you think we should go for RC2, which is available in the Git.

**Comment by ehmry** [comment]
netperf_lwip on base-linux gives me
```
[init] nic_drv: no route to service "Platform"
[init -> nic_drv] Uncaught exception of type 'Genode::Parent::Service_denied'
[init -> nic_drv] Warning: abort called - thread: ep
```

Which scenario are you running?

RC2 must have come out in the last week, I will give it a try.

**Comment by chelmuth** [comment]
I also do `make run/netperf_lwip`. But, your log looks strange as the Linux nic_drv does not need (and therefore does not request) the Platform service. May it be that you have a stale nic_drv binary from an old build?

**Comment by chelmuth** [comment]
With Gigabit Ethernet I measured on e34787b34f638880f0cebd5e9a875f61ef6222fa
* **2.0.0**
  * **TCP_STREAM** 238-257 MBit/s
  * **TCP_MAERTS** 22-47 MBit/s

**Comment by ehmry** [comment]
This would really confuse benchmarking, but an option for going forward could be to remove all libc socket compatibility for ``lib/lwip2`` and instead implement that in a ``lib/vfs/lwip``. That would remove some complexity from lwip and the awkward libc/lwip namespacing problems.

**Comment by chelmuth** [comment]
Sounds like a good direction. Could we assemble lwip in a static library for users of the raw API and move the namespacing to vfs_lwip which provides the socket interface? I'd like to avoid an additional lwip library just because of the namespace issues.

**Comment by ehmry** [comment]
Rebasing...

**Comment by ehmry** [comment]
Will close with #2335 or 3f7625674af0963ff51b64a2d9423d95cf7da046.

The TCP parameters still need to be tuned.

**Comment by chelmuth** [comment]
I removed the fixed label for now. Can be added later if we finished the lxip migration step.

**Comment by chelmuth** [comment]
Are there already fixups regarding my [comment](https://github.com/genodelabs/genode/commit/cf0d929fa643e2cf0936efd0b5f55bf0082af8c6#r29935341)?

**Comment by ehmry** [comment]
No, testing the download of large files in QEMU showed a negligible difference in performance compared to LxIP, and Wireshark analysis shows that the TCP window is adjusting close to the same range as LxIP. I still need to make a test on real hardware, but I have had issues with resolving, possibly just a mismatch between libraries.
